#!/usr/bin/env python3
"""
patch_model_registry.py -- separate frozen pre-registration from experimental
specs, make the separation mechanically verifiable, and close a live
contamination in the forward test.

THE URGENT PART
    config/models.yaml gained four `model_1_recency_*` entries on 2026-08-23,
    under the SAME `models:` key that forward_log.load_models() reads. The last
    logged signal is 2026-08-21 (Friday), so the NEXT forward_log run is the
    first that would see them.

    It would log all seven models. And because forward_log.picks_for() calls
    `_kw(dist, spec)` with NO age_years, analog_core._kw takes its
    `if hl is None or age_years is None: return sim` branch -- the recency term
    is never applied. The four recency models would therefore log picks
    BIT-IDENTICAL to model_1_baseline, under four different names, into a
    scoreboard presenting them as forward-tested recency variants.

    docs/prereg_recency_kernel.md section 5 states these are backtest-only until
    forward-test evidence exists. Running forward_log unpatched manufactures that
    evidence out of duplicates.

WHAT THIS PATCH DOES
    1. models.yaml: `models:` keeps ONLY the three frozen specs. The four
       recency variants move to a new top-level `backtest_models:` key.
    2. config/models.frozen.sha256: canonical checksum of the frozen block
       (yaml -> dict -> sorted JSON -> sha256). Whitespace- and comment-
       invariant, so the SPECS are what is protected, not the file's bytes.
    3. forward_log.py: load_models() verifies the checksum and dies on
       mismatch; picks_for() now passes age_years to _kw().
    4. model_grid.py: load_frozen_models() verifies the checksum and refuses
       any entry carrying half_life_years.
    5. analog_backtest.py: --half-life flag. Default None = read config, so a
       no-argument run stays BIT-IDENTICAL to the run that produced 0.51 / 0.25.

WHY A CHECKSUM AND NOT A COMMENT
    "Do not edit this file" is a social guarantee that was already broken on
    08-23. A checksum is verifiable by someone who has never read docs/, which
    is what a data vendor or a classification standard has to be able to offer.
    The pre-registration evidence is the CONTENT of model_1/2/3 plus commit
    ce18d34 -- both survive this patch untouched.

SAFETY
    Every anchor is asserted present and unique before any file is written. If
    one fails, nothing is written. Run --dry-run first.

Run from the repo root:
    python patch_model_registry.py --dry-run
    python patch_model_registry.py
"""
import argparse
import hashlib
import json
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent
MODELS_YAML = ROOT / "config" / "models.yaml"
SHA_FILE = ROOT / "config" / "models.frozen.sha256"

# Computed from the CURRENT models.yaml, frozen entries only (those with no
# half_life_years). Recorded here so the patch fails loud if the file it is
# about to split is not the file it was written against.
EXPECTED_FROZEN_SHA = "6b19b880f68c7f818798ae0c89e40b829e2fe7331bcf9e5dca31cb1597105fe1"

CHECKSUM_HELPER = '''

def frozen_sha256(models: dict) -> str:
    """Canonical checksum of the frozen model block.

    yaml -> dict -> sorted-key JSON -> sha256. Whitespace- and comment-
    invariant by construction: what is protected is the SPECS, not the file's
    bytes. Comments and key order may change freely; a single altered
    hyperparameter cannot.
    """
    import hashlib as _h, json as _j
    return _h.sha256(_j.dumps(models, sort_keys=True,
                              separators=(",", ":")).encode()).hexdigest()


def verify_frozen(models: dict, on_fail):
    """Compare the frozen block against config/models.frozen.sha256.

    Adding entries under `backtest_models:` is free. Touching a frozen spec is
    not: it changes this hash and every loader refuses to run.
    """
    sha_path = MODELS_YAML.parent / "models.frozen.sha256"
    if not sha_path.exists():
        on_fail(f"missing {sha_path} -- the frozen-block checksum. "
                f"Frozen specs cannot be verified; refusing to proceed.")
    want = sha_path.read_text().split()[0].strip()
    got = frozen_sha256(models)
    if got != want:
        on_fail(
            "FROZEN MODEL REGISTRY ALTERED.\\n"
            f"    expected {want}\\n"
            f"    got      {got}\\n"
            "    config/models.yaml `models:` block no longer matches its committed\\n"
            "    checksum. model_1/2/3 are pre-registration evidence for the running\\n"
            "    forward test (ce18d34) and are never edited. New models go under\\n"
            "    `backtest_models:`. If a frozen spec genuinely must change, that is a\\n"
            "    new pre-registration with a new commit, not an edit -- and the\\n"
            "    checksum is updated in the SAME commit with the reason in the message."
        )
    return got
'''

EDITS = []

# --- forward_log.py: checksum + namespace + the age_years fix --------------
EDITS.append((
    "src/forward_log.py",
    '''def load_models():
    if not MODELS_YAML.exists():
        die(f"missing {MODELS_YAML} -- the frozen model registry.")
    spec_file = yaml.safe_load(MODELS_YAML.read_text())["models"]
    out = {}
    for name, s in spec_file.items():
        d = dict(DEFAULT); d.update({k: v for k, v in s.items() if k != "note"})
        out[name] = d
    return out''',
    '''def frozen_sha256(models: dict) -> str:
    """Canonical checksum of the frozen model block.

    yaml -> dict -> sorted-key JSON -> sha256. Whitespace- and comment-
    invariant by construction: what is protected is the SPECS, not the file's
    bytes. Comments and key order may change freely; a single altered
    hyperparameter cannot.
    """
    import hashlib as _h, json as _j
    return _h.sha256(_j.dumps(models, sort_keys=True,
                              separators=(",", ":")).encode()).hexdigest()


def load_models():
    """Load ONLY the frozen pre-registered models, and verify they are intact.

    Reads `models:` and nothing else. Experimental specs live under
    `backtest_models:` and MUST NOT enter the live forward test -- see
    docs/prereg_recency_kernel.md section 5.

    Split 2026-08-24. Before that, four `model_1_recency_*` entries sat under
    `models:` and this function would have logged them live. Worse: picks_for()
    called `_kw(dist, spec)` with no age_years, so the recency term never
    applied and all four would have produced picks BIT-IDENTICAL to
    model_1_baseline under four different names. Caught before the first run
    that would have seen them.
    """
    if not MODELS_YAML.exists():
        die(f"missing {MODELS_YAML} -- the frozen model registry.")
    raw = yaml.safe_load(MODELS_YAML.read_text())
    if "models" not in raw:
        die(f"{MODELS_YAML} has no `models:` key -- the frozen registry is gone.")
    spec_file = raw["models"]

    # --- frozen-block integrity ------------------------------------------
    sha_path = MODELS_YAML.parent / "models.frozen.sha256"
    if not sha_path.exists():
        die(f"missing {sha_path} -- the frozen-block checksum. Frozen specs "
            f"cannot be verified; refusing to log live picks.")
    want = sha_path.read_text().split()[0].strip()
    got = frozen_sha256(spec_file)
    if got != want:
        die("FROZEN MODEL REGISTRY ALTERED.\\n"
            f"    expected {want}\\n"
            f"    got      {got}\\n"
            "    config/models.yaml `models:` no longer matches its committed checksum.\\n"
            "    model_1/2/3 are pre-registration evidence for THIS forward test\\n"
            "    (ce18d34) and are never edited. New models go under `backtest_models:`.\\n"
            "    Refusing to log picks against an altered registry.")

    # --- no experimental spec may reach the live path ---------------------
    leaked = sorted(n for n, s in spec_file.items() if "half_life_years" in s)
    if leaked:
        die(f"experimental spec(s) found under `models:`: {', '.join(leaked)}.\\n"
            f"    Entries carrying half_life_years are backtest-only "
            f"(docs/prereg_recency_kernel.md section 5).\\n"
            f"    Move them to `backtest_models:` before running the forward test.")

    out = {}
    for name, s in spec_file.items():
        d = dict(DEFAULT); d.update({k: v for k, v in s.items() if k != "note"})
        out[name] = d
    print(f"  frozen registry verified ({len(out)} models, sha {got[:12]})")
    return out''',
    "forward_log.load_models -- checksum, namespace guard, experimental-leak guard",
))

EDITS.append((
    "src/forward_log.py",
    '''    dist = np.linalg.norm(X[cand] - x_now, axis=1)
    w = _kw(dist, spec)''',
    '''    dist = np.linalg.norm(X[cand] - x_now, axis=1)
    # age_years MUST be passed. Omitting it silently disabled the recency term:
    # _kw returns the bare similarity kernel when age_years is None, so any spec
    # carrying half_life_years produced picks identical to the no-decay
    # baseline. Fixed 2026-08-24. This is a NO-OP for model_1/2/3, which carry
    # no half_life_years -- _kw still short-circuits on `hl is None` and returns
    # bit-identical weights, so no logged row changes. analog_core.current_picks
    # always passed age; only this path did not.
    age = (pos - cand) / 252.0          # sessions -> years
    w = _kw(dist, spec, age)''',
    "forward_log.picks_for -- pass age_years so recency actually applies",
))

# --- model_grid.py: checksum + refuse experimental specs -------------------
EDITS.append((
    "src/model_grid.py",
    '''def load_frozen_models():
    """Read the frozen pre-registered specs. Same parsing as forward_log.load_models,
    so the grid scores exactly what the live harness trades. NEVER edit models.yaml
    to match a new grid winner -- it is pre-registration evidence."""
    if not MODELS_YAML.exists():
        raise SystemExit(f"missing {MODELS_YAML} -- the frozen model registry.")
    raw = yaml.safe_load(MODELS_YAML.read_text())["models"]
    out = {}
    for name, s in raw.items():
        d = dict(DEFAULT); d.update({k: v for k, v in s.items() if k != "note"})
        out[name] = d
    return out''',
    '''def frozen_sha256(models: dict) -> str:
    """Canonical checksum of the frozen model block. See forward_log for the
    reference implementation; kept in sync deliberately rather than imported, so
    neither script can be broken by an edit to the other."""
    import hashlib as _h, json as _j
    return _h.sha256(_j.dumps(models, sort_keys=True,
                              separators=(",", ":")).encode()).hexdigest()


def load_frozen_models():
    """Read the frozen pre-registered specs. Same parsing as forward_log.load_models,
    so the grid scores exactly what the live harness trades. NEVER edit models.yaml
    to match a new grid winner -- it is pre-registration evidence.

    Reads `models:` ONLY. Experimental specs live under `backtest_models:`
    (split 2026-08-24). Before the split, four recency variants sat under
    `models:`, so this function returned SEVEN models, printed them all under
    the heading "THE THREE FROZEN PRE-REGISTERED MODELS", and -- because --out
    defaults to docs/model_grid_results.md -- would have overwritten the
    pre-registration record with backtest-only variants mixed into it.
    """
    if not MODELS_YAML.exists():
        raise SystemExit(f"missing {MODELS_YAML} -- the frozen model registry.")
    parsed = yaml.safe_load(MODELS_YAML.read_text())
    if "models" not in parsed:
        raise SystemExit(f"{MODELS_YAML} has no `models:` key.")
    raw = parsed["models"]

    sha_path = MODELS_YAML.parent / "models.frozen.sha256"
    if not sha_path.exists():
        raise SystemExit(f"missing {sha_path} -- the frozen-block checksum.")
    want = sha_path.read_text().split()[0].strip()
    got = frozen_sha256(raw)
    if got != want:
        raise SystemExit(
            "FROZEN MODEL REGISTRY ALTERED.\\n"
            f"  expected {want}\\n  got      {got}\\n"
            "  models.yaml `models:` no longer matches its committed checksum. It is\\n"
            "  pre-registration evidence and is never edited to match a new winner.")

    leaked = sorted(n for n, s in raw.items() if "half_life_years" in s)
    if leaked:
        raise SystemExit(
            f"experimental spec(s) under `models:`: {', '.join(leaked)}.\\n"
            f"  Entries carrying half_life_years are backtest-only and must not be\\n"
            f"  written into the frozen pre-registration record.\\n"
            f"  Move them to `backtest_models:`.")

    out = {}
    for name, s in raw.items():
        d = dict(DEFAULT); d.update({k: v for k, v in s.items() if k != "note"})
        out[name] = d
    print(f"frozen registry verified: {len(out)} models, sha {got[:12]}")
    return out''',
    "model_grid.load_frozen_models -- checksum + experimental-leak guard",
))

# --- analog_backtest.py: the --half-life flag -----------------------------
EDITS.append((
    "src/analog_backtest.py",
    '''    ap.add_argument("--min-analogs", type=int, default=20)
    ap.add_argument("--min-cov", type=int, default=10)
    args = ap.parse_args()''',
    '''    ap.add_argument("--min-analogs", type=int, default=20)
    ap.add_argument("--min-cov", type=int, default=10)
    ap.add_argument("--half-life", type=float, default=None, metavar="YEARS",
                    help="recency half-life in YEARS. Converted to a per-session "
                         "lambda as ln2/(HL*252). Pass 'inf' for NO decay. "
                         "DEFAULT None = read analog.recency_decay_lambda from "
                         "config.yaml (0.0008/session, HL 3.44y), so a "
                         "no-argument run is BIT-IDENTICAL to the run that "
                         "produced the recorded 0.51 / 0.25.")
    args = ap.parse_args()''',
    "analog_backtest -- add --half-life flag",
))

EDITS.append((
    "src/analog_backtest.py",
    '''    sigma = float(cfg["analog"]["similarity_sigma"])
    lam = float(cfg["analog"]["recency_decay_lambda"])
    rng = np.random.default_rng(cfg["project"]["random_seed"])''',
    '''    sigma = float(cfg["analog"]["similarity_sigma"])

    # --- recency decay ----------------------------------------------------
    # config's recency_decay_lambda is a PER-SESSION lambda with UNKNOWN
    # provenance: 0.0008 => HL = ln2/0.0008 = 866 sessions = 3.44 years. It is
    # off the registered ladder in docs/prereg_recency_kernel.md and is reported
    # as THE INCUMBENT, never as a rung. The recorded 0.51 / 0.25 carry it.
    # --half-life overrides it for the ladder sweep; the default path is
    # untouched so the headline figures stay reproducible from this repo.
    if args.half_life is None:
        lam = float(cfg["analog"]["recency_decay_lambda"])
        lam_src = (f"config recency_decay_lambda={lam:g}/session "
                   f"(HL {np.log(2)/lam/252:.2f}y) -- INCUMBENT, unregistered")
    elif np.isinf(args.half_life):
        lam = 0.0
        lam_src = "NO DECAY (HL = inf) -- ladder control rung"
    else:
        if args.half_life <= 0:
            raise SystemExit("--half-life must be positive, or inf for no decay.")
        lam = float(np.log(2.0) / (args.half_life * 252.0))
        lam_src = (f"HL {args.half_life:g}y -> lambda {lam:.6g}/session "
                   f"-- ladder rung")
    rng = np.random.default_rng(cfg["project"]["random_seed"])''',
    "analog_backtest -- resolve lambda from flag or config, provenance recorded",
))

EDITS.append((
    "src/analog_backtest.py",
    '''    print(f"horizon {H}d | basket {N}/side | expanding window, refit every "
          f"{args.refit_every}d | {args.iters} permutations")''',
    '''    print(f"horizon {H}d | basket {N}/side | expanding window, refit every "
          f"{args.refit_every}d | {args.iters} permutations")
    print(f"recency:  {lam_src}")
    print(f"features: RAW PC values (not z-scored) -- a different basis from "
          f"analog_core/model_grid")''',
    "analog_backtest -- print the decay basis in the run header",
))


def split_models_yaml(dry_run: bool):
    """Move half_life_years entries from `models:` to `backtest_models:`, and
    write the frozen-block checksum. Text-level edit: comments are preserved."""
    if not MODELS_YAML.exists():
        return [f"MISSING FILE: {MODELS_YAML}"]

    text = MODELS_YAML.read_text()
    parsed = yaml.safe_load(text)
    if "models" not in parsed:
        return [f"{MODELS_YAML} has no `models:` key"]
    if "backtest_models" in parsed:
        print("  ok    config/models.yaml: already split (backtest_models: present)")
        return []

    raw = parsed["models"]
    frozen = {k: v for k, v in raw.items() if "half_life_years" not in v}
    exp = {k: v for k, v in raw.items() if "half_life_years" in v}

    got = hashlib.sha256(json.dumps(frozen, sort_keys=True,
                                    separators=(",", ":")).encode()).hexdigest()
    if got != EXPECTED_FROZEN_SHA:
        return [f"frozen block hashes to {got}, patch was written against "
                f"{EXPECTED_FROZEN_SHA} -- models.yaml has changed. "
                f"Re-derive before applying."]

    marker = ("  # --- recency-weighted variants, added 2026-08-23 "
              "-----------------------")
    if marker not in text:
        return [f"split marker comment not found in {MODELS_YAML}"]
    if text.count(marker) != 1:
        return [f"split marker not unique in {MODELS_YAML}"]

    print(f"  ok    config/models.yaml: {len(frozen)} frozen, "
          f"{len(exp)} to move ({', '.join(exp)})")
    print(f"  ok    config/models.frozen.sha256: {got[:16]}...")

    if dry_run:
        return []

    head, tail = text.split(marker, 1)
    # NO de-indent: entries sit at 2-space indent under `models:` and need the
    # same indent under `backtest_models:`. Stripping it pushed all four to
    # top-level keys and left backtest_models: empty (caught in test 2026-08-24).
    moved = tail
    new = head.rstrip() + """

# ===========================================================================
# EXPERIMENTAL / BACKTEST-ONLY MODELS
# ===========================================================================
# SPLIT OUT OF `models:` 2026-08-24. These four entries were added under
# `models:` on 08-23. forward_log.load_models() reads `models:`, so the next
# forward_log run -- the first since they were added -- would have logged all
# seven models live. And because picks_for() passed no age_years to _kw(), the
# recency term never applied: all four would have produced picks BIT-IDENTICAL
# to model_1_baseline under four different names, in a scoreboard presenting
# them as forward-tested recency variants.
#
# Nothing here is read by the live forward test. Adding entries below is free.
# Editing anything under `models:` above changes config/models.frozen.sha256
# and every loader refuses to run.
#
# See docs/prereg_recency_kernel.md sections 3, 5 and 7.
# ===========================================================================

backtest_models:
""" + moved.rstrip() + "\n"

    MODELS_YAML.write_text(new)
    print("  written  config/models.yaml (split)")

    SHA_FILE.write_text(
        f"{got}  config/models.yaml::models\n"
        "# Canonical checksum of the FROZEN model block: yaml -> dict ->\n"
        "# sorted-key JSON -> sha256. Whitespace- and comment-invariant, so what\n"
        "# is protected is the SPECS, not the file's bytes. Verified by\n"
        "# forward_log.load_models() and model_grid.load_frozen_models(); both\n"
        "# refuse to run on mismatch.\n"
        "#\n"
        "# Covers model_1_baseline, model_2_horizon_trend, model_3_overfit --\n"
        "# pre-registration evidence for the live forward test, first committed\n"
        "# ce18d34 2026-08-17 14:24:09 +0800. Adding models under\n"
        "# `backtest_models:` does not change this hash. Changing a frozen\n"
        "# hyperparameter does, and that is the point.\n")
    print(f"  written  config/models.frozen.sha256")
    return []


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--dry-run", action="store_true")
    args = ap.parse_args()

    print("=" * 74)
    print("PHASE 1 -- verifying every anchor (nothing is written)")
    print("=" * 74)
    failures = []
    for path, anchor, _r, label in EDITS:
        p = ROOT / path
        if not p.exists():
            failures.append(f"MISSING FILE: {path}  [{label}]")
            print(f"  FAIL  {path}: not found"); continue
        n = p.read_text().count(anchor)
        if n == 0:
            failures.append(f"ANCHOR NOT FOUND in {path}  [{label}]")
            print(f"  FAIL  {path}: anchor not found -- {label}")
            print(f"        sought: {anchor[:70]!r}")
        elif n > 1:
            failures.append(f"ANCHOR NOT UNIQUE ({n}x) in {path}  [{label}]")
            print(f"  FAIL  {path}: anchor x{n}, must be unique -- {label}")
        else:
            print(f"  ok    {path}: {label}")

    failures += split_models_yaml(dry_run=True)

    if failures:
        print("\n" + "=" * 74)
        print(f"ABORTED -- {len(failures)} failure(s). NO FILE WAS MODIFIED.")
        print("=" * 74)
        for f in failures:
            print(f"  - {f}")
        sys.exit(1)

    print(f"\nall {len(EDITS)} anchors verified, unique.")
    if args.dry_run:
        print("\n--dry-run: nothing written.")
        return

    print("\n" + "=" * 74)
    print("PHASE 2 -- applying")
    print("=" * 74)
    touched = {}
    for path, anchor, repl, label in EDITS:
        p = ROOT / path
        text = touched.get(path, p.read_text())
        assert text.count(anchor) == 1, f"anchor lost mid-run: {path} [{label}]"
        touched[path] = text.replace(anchor, repl)
        print(f"  applied  {path}: {label}")
    for path, text in touched.items():
        (ROOT / path).write_text(text)
        print(f"  written  {path}")

    split_models_yaml(dry_run=False)

    print("\n" + "=" * 74)
    print("""VERIFY BEFORE COMMITTING -- do not assume:

  python -m src.forward_log --dry-run
      Expect exactly THREE models and a line reading
      "frozen registry verified (3 models, sha 6b19b880f68c)".
      Seven models, or no verification line, means the patch did not take.

  python -m src.analog_backtest --iters 50
      Header must read "INCUMBENT, unregistered". Sharpe must match the
      recorded 0.51 / 0.25 -- the default path is unchanged.

  python -m src.analog_backtest --half-life inf --iters 50
      The number that has never existed: the headline engine with NO decay.

  git diff --stat

Suggested commit:

  git add config/models.yaml config/models.frozen.sha256 \\\\
          src/forward_log.py src/model_grid.py src/analog_backtest.py
  git commit -m "registry: split frozen models from experimental; add
  verified frozen-block checksum; fix forward_log logging four recency
  variants as duplicates of model_1_baseline (age_years never passed to
  _kw); add --half-life to analog_backtest for the ladder sweep"
""")
    print("=" * 74)


if __name__ == "__main__":
    main()
